# You're playlist file that you exported from iTunes.
playlist: /tmp/playlist.xml

# The codecs that your mp3 player supports. The first is what your unsupported
# files will be encoded to.
supported_codecs:
  - mp3
  - aac

# Where to save your files.
#   %A    album
#   %a    artist
#   %e    file extension
#   %g    genre
#   %n    track number
#   %t    song title
#   %y    year
library_path: '/tmp/library/%a/[%y] %A/%n-%t.%e'

# Instead of copying files, create symlinks.
symlink_for_copy: true
